### ISSUE TITLE
Gebruik meer specifieke selectors in je CSS file, om de velden in je menu te stylen

### ISSUE THREAD

**Issue by JeroenHeemskerk** [hanaalkadri/educom-webshop-basis#20]
In de CSS worden ALLE `<a>` tags aangepast, voor aanpassingen die ALLEEN voor het menu zijn
https://github.com/hanaalkadri/educom-webshop-basis/blob/daaccdccd5d7752986665ec533330b7a829a919b/CSS/stylesheet.css#L13-L32
Door de `<li>` tag (eigenlijk `<ul>` tag zie issue #11) een class te geven kan je preciezer zijn in je CSS.
Daarnaast kan je in CSS selectors die dezelfde inhoud hebben (zoals a:link, a:visited, etc) kan je achter elkaar zetten. 
https://github.com/hanaalkadri/educom-webshop-basis/blob/daaccdccd5d7752986665ec533330b7a829a919b/index.html#L13-L15
aanpast naar 
```HTML
      <li class="menu"> 
        <ul>
          <a href="./index.html"> Home </a>  
```
Kan je in je CSS iets zetten als 
```CSS
.menu a:link, .menu a:visited, .menu a:hover, .menu a:active { 
  text-decoration: none; 
}
.menu a { 
  /* ... blue ... */ 
}
```
